<a href="https://colab.research.google.com/github/angelinayhl/Python385/blob/master/HW_ReadingBooks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## QTM 101: Sample homework

## Welcome to the QTM 101 sample homework.
What you are looking at is called a notebook. It consists of cells. There are two types of cells.


### Markdown cells
Try double clicking the text "QTM 101" above. You should see 

```# QTM 101: Sample homework```

appear. This is a **Markdown** cell. It consists of text together with simple commands for formatting the text. For instance, try replacing the hashtag with two hashtags, that is, type

```## QTM 101: Sample homework```

Notice the difference? There are three header sizes corresponding to #, ##, or ### preceding a line of text.

### Code cells
Now click the triangle on the cell below. It is a **code** cell. It will run a program called pip which will install a package called datascience.

In [0]:
!pip install datascience

##Next code cell
The code in the cell below is written in the programming language Python. It is an excellent language for beginners thanks to its almost literal syntax. Nevertheless, it is a very powerful tool and extremely popular across a wide spectrum of users. You can do almost anything in Python!  

In [0]:
# load the datascience package as well as other functions we need to use
from datascience import *
from datascience.predicates import are
import numpy as np
import matplotlib
matplotlib.use('Agg', warn=False)
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

from urllib.request import urlopen 
import re
def read_url(url): 
    return re.sub('\\s+', ' ', urlopen(url).read().decode())

Example: Plotting the Classics 
------------------------------
Material presented from the textbook, *Computational and Inferential Thinking*, by Ani Adhikari and John DeNero.

In [0]:
huck_finn_url = 'http://www.gutenberg.org/files/76/old/2011-05-03-76.txt'
huck_finn_text = urlopen(huck_finn_url).read().decode()

# Then split it into chapters
**Exercise:** Split huck_finn_text into chapters by replacing the blank lines with the correct code. Test your solution is correct by comparing with the expected output which shows the first ten characters (not literary characters) of the first three chapters.

Note, the first appearance of CHAPTER in the text is not the first Chapter!

In [0]:
hf_chapters = huck_finn_text.split('CHAPTER ')[1:]

print(hf_chapters[0][:10])
print(hf_chapters[1][:10])
print(hf_chapters[2][:10])

I.

YOU 
II.

WE 
III.

WE


**Expected Output**: 

<table style="width:50%">
  <tr>
    <td>    <code>print(hf_chapters[0][:10])<code></td>
    <td>    <code>I. YOU don<code></td> 
  </tr>
  <tr>
    <td><code>print(hf_chapters[1][:10])<code></td>
    <td><code>II. WE wen<code></td> 
  </tr>
  <tr>
    <td><code>print(hf_chapters[2][:10])<code></td>
    <td><code>III. WELL,<code></td> 
  </tr>
</table>

In [0]:
Table().with_column('Chapters', hf_chapters)

Chapters
I.

YOU don't know about me without you have read a bo ...
II.

WE went tiptoeing along a path amongst the trees  ...
III.

WELL, I got a good going-over in the morning fro ...
IV.

WELL, three or four months run along, and it was  ...
V.

I HAD shut the door to.  Then I turned around and  ...
VI.

WELL, pretty soon the old man was up and around a ...
VII.

"GIT up!  What you 'bout?"

I opened my eyes a ...
VIII.

THE sun was up so high when I waked that I judg ...
IX.

I WANTED to go and look at a place right about th ...
X.

AFTER breakfast I wanted to talk about the dead ma ...
... (33 rows omitted)

## Counting Names 
In the next exercise you will use the np.char.count() function from the Numpy library. If you don't know how to use it, try running the code in the cell below to read the Numpy library's documentation! 

In [0]:
import numpy as np
help(np.char.count)

Help on function count in module numpy.core.defchararray:

count(a, sub, start=0, end=None)
    Returns an array with the number of non-overlapping occurrences of
    substring `sub` in the range [`start`, `end`].
    
    Calls `str.count` element-wise.
    
    Parameters
    ----------
    a : array_like of str or unicode
    
    sub : str or unicode
       The substring to search for.
    
    start, end : int, optional
       Optional arguments `start` and `end` are interpreted as slice
       notation to specify the range in which to count.
    
    Returns
    -------
    out : ndarray
        Output array of ints.
    
    See also
    --------
    str.count
    
    Examples
    --------
    >>> c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
    >>> c
    array(['aAaAaA', '  aA  ', 'abBABba'],
        dtype='|S7')
    >>> np.char.count(c, 'A')
    array([3, 1, 1])
    >>> np.char.count(c, 'aA')
    array([3, 1, 0])
    >>> np.char.count(c, 'A', start=1, end=4)
    array([2, 1,

**Exercise:** Create an array that contains a count of the number of times the name Jim appears in each chapter. 

In [0]:
count_jim = np.char.count(hf_chapters, 'Jim')

# How many times Jim appears in Chapters 1, 9, and 19
print(count_jim[0])
print(count_jim[10])
print(count_jim[20])

0
4
1


**Expected Output**: 

<table style="width:50%">
  <tr>
    <td>    <code>count_jim[0]<code></td>
    <td>    <code>0<code></td> 
  </tr>
  <tr>
    <td><code>count_jim[10]<code></td>
    <td><code>4<code></td> 
  </tr>
  <tr>
    <td><code>count_jim[20]<code></td>
    <td><code>1<code></td> 
  </tr>
</table>

# Read Little Women and split into chapters
**Exercise:** Load Little women and split into chapters by replacing the blank lines with the correct code.

In [0]:
little_women_url = 'http://www.gutenberg.org/cache/epub/514/pg514.txt'
little_women_text = urlopen(little_women_url).read().decode()
lw_chapters = little_women_text.split('CHAPTER ')[1:]

print(lw_chapters[0][:10])
print(lw_chapters[1][:10])
print(lw_chapters[2][:10])

ONE

PLA
TWO

A M
THREE

T


**Expected Output**: 

<table style="width:50%">
  <tr>
    <td>    <code>print(hf_chapters[0][:10])<code></td>
    <td>    <code>ONE PLAYIN<code></td> 
  </tr>
  <tr>
    <td><code>print(hf_chapters[1][:10])<code></td>
    <td><code>TWO A MERR<code></td> 
  </tr>
  <tr>
    <td><code>print(hf_chapters[2][:10])<code></td>
    <td><code>THREE THE <code></td> 
  </tr>
</table>

In [0]:
Table().with_column('Chapters', lw_chapters)

Chapters
ONE

PLAYING PILGRIMS

"Christmas won't be Christmas ...
TWO

A MERRY CHRISTMAS

Jo was the first to wake in  ...
THREE

THE LAURENCE BOY

"Jo!  Jo!  Where are you?"  ...
FOUR

BURDENS

"Oh, dear, how hard it does seem to t ...
FIVE

BEING NEIGHBORLY

"What in the world are you g ...
SIX

BETH FINDS THE PALACE BEAUTIFUL

The big house  ...
SEVEN

AMY'S VALLEY OF HUMILIATION

"That boy is a p ...
EIGHT

JO MEETS APOLLYON

"Girls, where are you goin ...
NINE

MEG GOES TO VANITY FAIR

"I do think it was th ...
TEN

THE P.C. AND P.O.

As spring came on, a new set ...
... (37 rows omitted)

# Counts of names by chapter for Little Women
**Exercise:** Complete the code by filling in the blanks to create a dictionary having keys the names 'Amy', 'Beth', 'Jo', 'Laurie', 'Meg' and values arrays containing the number of times that name appears in each chapter.

In [0]:
people = [___________]
people_counts = {pp: ___________ for pp in people}

# Create a table using the dictionary you created
counts = Table().with_columns([
        'Amy', people_counts['Amy'],
        'Beth', people_counts['Beth'],
        'Jo', people_counts['Jo'],
        'Laurie', people_counts['Laurie'],
        'Meg', people_counts['Meg']
    ])

# Plot the cumulative counts.
**Exercise:** Complete the code by filling in the blanks to create a plot having the title:

Cumulative Number of Times Name Appears.

In [0]:
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

cum_counts = __________.cumsum().with_column('Chapter', np.arange(1, 48, 1))
______________.plot(column_for_xticks=5)
plots.title(________________)