<a href="https://colab.research.google.com/github/angelinayhl/Python385/blob/master/Numpy_arrays_exercise_book.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy arrays exercise book

The material we present is from the official Python documentation (see https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences)
as well Datacamp (https://www.datacamp.com/community/tutorials/18-most-common-python-list-questions-learn-python#gs.w3PIMoY

So far we have learned basic facts on functions, strings, and lists. You will apply them in this next exercise.

**Exercise** Write a simple function which checks if a string (you may assume it is given with no punctuation) is a palindrome and returns "This is a palindrome" if it is, else "This is not a palindrome" if not.

In [0]:
def pal(wrd):
    wrd_no_space = ___
    rvs_wrd = ___
    return "This is a palindrome" if rvs_wrd == wrd_no_space else "This is not a palindrome"

In [0]:
# test 
print("pal('racecar'): " + str(pal('racecar')))
print("pal('palindrome'): " + str(pal('palindrome')))
print("pal('a dog a plan a canal pagoda'): " + str(pal('a dog a plan a canal pagoda')))

pal('racecar'): This is a palindrome
pal('palindrome'): This is a palindrome
pal('a dog a plan a canal pagoda'): This is a palindrome


**Expected output for test**:  
<code>
pal('racecar'): This is a palindrome  
pal('palindrome'): This is not a palindrome
pal('a dog a plan a canal pagoda'): This is a palindrome
</code>

### Tuples
A tuple consists of a number of values separated by commas, for instance:

In [0]:
t = 12345, 54321, 'hello!'
t[0]

12345

In [0]:
t

(12345, 54321, 'hello!')

In [0]:
# Tuples may be nested:
u = t, (1, 2, 3, 4, 5)
u

((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))

In [0]:
# Tuples are immutable:
t[0] = 88888

TypeError: 'tuple' object does not support item assignment

In [0]:
# but they can contain mutable objects:
v = ([1, 2, 3], [3, 2, 1])

In [0]:
v

([1, 2, 3], [3, 2, 1])

As you see, on output tuples are always enclosed in parentheses.

## Dictionaries

In [0]:
tel = {'jack': 4098, 'sape': 4139}

In [0]:
tel['guido'] = 4127

In [0]:
tel

{'guido': 4127, 'jack': 4098, 'sape': 4139}

In [0]:
 tel['jack']

4098

In [0]:
del tel['sape']

In [0]:
list(tel.keys())

['jack', 'guido']

In [0]:
sorted(tel.keys())

['guido', 'jack']

In [0]:
'guido' in tel

True

In [0]:
'jack' not in tel

False

The `dict()` constructor builds dictionaries directly from sequences of key-value pairs:

In [0]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'guido': 4127, 'jack': 4098, 'sape': 4139}

In addition, dict comprehensions can be used to create dictionaries from arbitrary key and value expressions:

In [0]:
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

## When To Use Python Lists And When To Use Tuples, Dictionaries Or Sets

### Lists Versus Tuples

### extend and append 

extend(), on the one hand, takes an iterable (that’s right, it takes a list, set, tuple or string!), and adds each element of the iterable to the list one at a time.

append(), on the other hand, adds its argument to the end of the list as a single item, which means that when the append() function takes an iterable as its argument, it will treat it as a single object.

Study the code chunks below and play around with the code for yourself to understand the differences between these two methods:

In [0]:
# extend [4,5] to `shortList`
firstlist = [1,2,3]
firstlist.extend([4, 5])
print(firstlist)

[1, 2, 3, 4, 5]


In [0]:
# Append [4,5] to `shortList`
shortlist = [1,2,3]
shortlist.append([4, 5])
print(shortlist)

[1, 2, 3, [4, 5]]


### Concatenate lists
To concatenate lists, you use the + operator. It will give you a new list that is the concatenation of your two lists without modifying the original ones.

Note that concatenating and appending might be confusing. append() is different from the + operator, which in its turn is very similar to the extend() method, but not exactly the same… You see that with append() and extend(), you modify your original list, while with the + operator, you can make another list variable

In [0]:
# Concatenate `shortList` with `[4,5]`
secondlist = [1,2,3]
pluslist = secondlist + [4,5]

#Use the `print()` method to see `plusList`
print(pluslist)
print(secondlist)

[1, 2, 3, 4, 5]
[1, 2, 3]


### Cloning or copying lists

* You can slice your original list and store it into a new variable: newList = oldList[:]
* You can use the built-in list() function: newList = list(oldList)
* You can use the copy library: With the copy() method newList = copy.copy(oldList)
If your list contains objects and you want to copy those as well, you can use copy.deepcopy(): copy.deepcopy(oldList)

Try it out below! 

In [0]:
groceries = ['bread', 'milk', 'eggs']
# Copy the grocery list by slicing and store it in the `newGroceries` variable
newGroceries = groceries
# Copy the grocery list with the `list()` function and store it in a `groceriesForFriends` variable
groceriesForFriends = list(groceries)
groceriesForFriends[0] = 'french bread'
print(groceriesForFriends)
print(groceries)
newGroceries[0] = 'french bread'
print(groceries)

['french bread', 'milk', 'eggs']
['bread', 'milk', 'eggs']
['french bread', 'milk', 'eggs']


### List Comprehensions
List comprehension is, basically speaking, a way of elegantly constructing your lists. The best thing about this for those who love math is the fact that they look a lot like mathematical lists. Judge for yourself:

In [0]:
[x**2 for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

What if you want to square only the even numbers? You just add a condition, indicated by `if`, to your original statement. If that condition proves to be `TRUE`, the number will be considered for squaring. In this case, our condition is that the number can be divided by 2 (without having any remainder of the division operation)

In [0]:
# square only the even numbers 
[x**2 for x in range(10) if x%2==0]

[0, 4, 16, 36, 64]

### How To Count Occurrences Of A List Item

In [0]:
# Count the occurrences of the letter "a"
letter_list = ["d", "a", "t", "a", "c", "a", "m", "p"]
letter_list.count("a")

3

In [0]:
ab_list= ["a","b","b"]
[[x,ab_list.count(x)] for x in set(ab_list)]

[['a', 1], ['b', 2]]

In this piece of code, you first see that your list is converted to a `set`. This will make sure that only the unique list items are kept, namely a and b. Then you say that for each set item, you want to take that item and pass it to a `count()` method

Alternatively, there’s the faster `Counter()` method from the collections library:

In [0]:
# Import `Counter` from the `collections` library
from collections import Counter
list_c = ["a","b","b"]
# Pass `list` to `Counter()`
Counter(list_c)

Counter({'a': 1, 'b': 2})

### List Intersection Using List Comprehension

If you want to obtain the intersection of two lists, you can use the `set` $\&$ intersection.

This is illustrated in the exercise below. 

In [0]:
# An intersection of both lists, stored in `intersection`
list1 = [x for x in range(100) if x%7 == 0]
list2 = [x for x in range(100) if x%5 == 0]
# Make use of the list and set data structures
print(list(set(list1) & set(list2)))

[0, 35, 70]


### Remove Duplicates From A List

As described earlier, it’s best to select a set if you want to store a unique collection of unordered items.

To create a set from any iterable, you can simply pass it to the built-in set() function. If you later need a real list again, you can similarly pass the set to the list() function.

**Exercise** Print the `duplicates` list without duplicates

In [0]:
# Your list with duplicate values
duplicates = [1, 2, 3, 1, 2, 5, 6, 7, 8]

# Print the list without duplicates
print(_____)

**Exercise** Print the `duplicates` list without the elements from the `smallNumbers` list

In [0]:
# A list with small numbers 
smallNumbers = [1, 2, 3]

# Print the unique `duplicates` list without the small numbers
list(set(duplicates) - set(____))

NameError: name '____' is not defined

### Numpy exercises

**Exercise** Import the numpy package under the name np

In [0]:
import numpy  as np

Print the numpy version and the configuration

In [3]:
print(np.__version__)
np.show_config()

1.14.6
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blis_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
lapack_mkl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE


**Exercise** Create a zero-vector in $\mathbb{R}^{10}$

In [7]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Exercise** Create a null vector of size 10 but the fifth value which is 1

In [8]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [0]:
#Alternate solution:
z = np.array([0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0])
print(z)

**Exercise** Create a 3x3 zero-matrix. Note `reshape` shapes

In [19]:

z = np.zeros(9).reshape(3,3)
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Exercise** Create a 3x3 matrix with random values

In [17]:
z = np.random.random((3,3))
print(z)

[[0.87857601 0.88058475 0.54137265]
 [0.37875241 0.47617124 0.27964255]
 [0.54777192 0.86266825 0.06573186]]


**Exercise** Create a 10x10 array with random values and find the minimum and maximum values

In [18]:
z = np.random.random((10,10))
z_max, z_min = z.max(), z.min()
print('maximum value is {} and the minimum value is {}'.format(z_max, z_min))

maximum value is 0.997883703551 and the minimum value is 0.00520534806226


**Exercise** Create random vector of size 10 and replace the maximum value by 0

In [22]:
z = np.random.random(10)
z[z.argmax()] = 0
print(z)

[0.91571461 0.70809107 0.68825673 0.         0.27231252 0.88689409
 0.75279042 0.79484469 0.90213892 0.28856949]


**Exercise** How to read the following file? 

In [0]:
from io import BytesIO

data = BytesIO("1,2,3,4,5,7,8,9,10,11")
z = np.genfromtxt(data, delimiter=",", dtype='unicode')

### Distance between points exercises

We're going to need an implementation of the $k$-nearest neighbor classifier.  In practice you would probably use an existing library, but it's simple enough that we're going to implement it.

The first thing we need is a way to compute the distance between two points.  How do we do this?  In 2-dimensional space, it's pretty easy.  If we have a point at coordinates $(x_0,y_0)$ and another at $(x_1,y_1)$, the distance between them is

$$D = \sqrt{(x_0-x_1)^2 + (y_0-y_1)^2}.$$

(Where did this come from?  It comes from the Pythogorean theorem: we have a right triangle with side lengths $x_0-x_1$ and $y_0-y_1$, and we want to find the length of the diagonal.)

In [0]:
# import modules we will need
import math
import numpy as np

**Exercise 1**: implement a Python function to compute this distance function by filling in the blanks below

In [0]:
def distance(pt1, pt2):
    total = 0
    for i in np.arange(len(pt1)):
        total = total + (pt1[i] - pt2[i])**2
    return math.sqrt(total)

In [34]:
# function test
print ("distance((0,0),(0,0)): " + str(distance((0,0),(0,0))))
print ("distance((1,0),(0,0)): " + str(distance((1,0),(0,0))))
print ("distance((0,3),(4,0)): " + str(distance((0,3),(4,0))))

distance((0,0),(0,0)): 0.0
distance((1,0),(0,0)): 1.0
distance((0,3),(4,0)): 5.0


**Expected output for test**: 

<code>distance((0,0),(0,0))</code>: <code>0.0 </code>   
<code>distance((1,0),(0,0))</code>: <code>1.0 </code>  
<code>distance((0,3),(4,0))</code>: <code>5.0 </code>

**Exercise 2**: implement in a new way a Python function to compute distance by filling in the blanks below

In [0]:
def distance2(pt1, pt2):
    x = np.array(pt1)
    y = np.array(pt2)
    return float(np.sum((x - y)**2))

In [39]:
# function test
print ("distance((0,0),(0,0)): " + str(distance2((0,0),(0,0))))
print ("distance((1,0),(0,0)): " + str(distance2((1,0),(0,0))))
print ("distance((0,3),(4,0)): " + str(distance2((0,3),(4,0))))

distance((0,0),(0,0)): 0.0
distance((1,0),(0,0)): 1.0
distance((0,3),(4,0)): 25.0


**Expected output for test**: 

<code>distance((0,0),(0,0))</code>: <code>0.0 </code>   
<code>distance((1,0),(0,0))</code>: <code>1.0 </code>  
<code>distance((0,3),(4,0))</code>: <code>5.0 </code>

## Higher dimensions
In 3-dimensional space, the formula for the distance $D$ between two points, $\text{pt}_0 = (x_0, y_0, z_0)$ and $\text{pt}_1 = (x_1,y_1, z_1)$, is 

$$D = \sqrt{(x_0-x_1)^2 + (y_0-y_1)^2 + (z_0-z_1)^2}.$$

In $k$-dimensional space, things are a bit harder to visualize, but I think you can see how the formula generalized: we sum up the squares of the differences between each individual coordinate, and then take the square root of that. 

**Exercise 3**: implement a Python function to compute distance between points in k-dimensional space, any k.

In [0]:
def distance(pt1,pt2):
   total = 0
   for i in np.arange(len(pt1)):
    total = total + (pt1[i] - pt2[i])**2
   return math.sqrt(total)
   
   
    

Hint: you may also try using np.subtract(__,__) as it takes two tuples and returns, as a Numpy array, their difference.

In [45]:
# function test
print ("distance((0,0,0),(0,0,0)): " + str(distance((0,0,0),(0,0,0))))
print ("distance((1,0,0),(0,0,0)): " + str(distance((1,0,0),(0,0,0))))
print ("distance((3,0,12),(0,4,0)): " + str(distance((3,0,12),(0,4,0))))

distance((0,0,0),(0,0,0)): 0.0
distance((1,0,0),(0,0,0)): 1.0
distance((3,0,12),(0,4,0)): 13.0



**Expected output for test**:  
<code>
distance((0,0,0),(0,0,0)): 0.0      
distance((1,0,0),(0,0,0)): 1.0  
distance((3,0,12),(0,4,0)): 13.0
</code>
